services:
  redis:
    image: redis:7-alpine
    container_name: billing_backend_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: billing_backend_web
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    depends_on:
      redis:
        condition: service_healthy
    # Remove command override to use the entrypoint script
    # command: ./bin/rails server -b 0.0.0.0
    stdin_open: true
    tty: true

volumes:
  redis_data:
  bundle_cache:
