[build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.envs]
RAILS_ENV = "production"
RAILS_SERVE_STATIC_FILES = "true"
