development:
  adapter: redis
  url: <%= RedisConfig.url %>
  channel_prefix: billing_backend_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= RedisConfig.url %>
  channel_prefix: billing_backend_production
