default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "devtestdatabase.contalink.com" } %>
  database: <%= ENV.fetch("DATABASE_NAME") { "testinvoices" } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "developer" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "UQpaA9TA" } %>

development:
  <<: *default

test:
  <<: *default

# Production configuration for Railway
production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>
  sslmode: require
